spring:
  application:
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
  jvm:
    encoding: UTF-8
server:
  # 端口
  port: 8088
ark: #方舟相关配置
  log:
    dir: 'D:\test\'
    file: 'log'
  notice:
    groupId: '637485030' # 群组ID
    combineLine: 3 # 合并发送的消息条数

qq: #qq相关配置
  ip: 127.0.0.1
  httpPort: 5700
  webSocketPort: 8080
  groupPeriod: 10 # 群组消息定时发送