spring:
  application:
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
  jvm:
    encoding: UTF-8
server:
  # 端口
  port: 8088
ark: #方舟相关配置
  log:
    dir: 'D:\test\'
    file: 'log'
  run: 'E:\ARK\steamCMD\Servers\Server2\ShooterGame\Saved\Config\WindowsServer\RunServer.cmd'
  name: 'ShooterGameServer.exe'
  notice:
    groupId: '637485030' # 群组ID
    combineLine: 6 # 合并发送的消息条数
n2n:
  run: 'D:\software\EasyN2N\n2n_client\x64\connect.bat'#运行脚本的位置
  name: 'edge_v3_bugxia_n2n.exe'#应用程序名称
qq: #qq相关配置
  number: '1684661146'
  ip: 127.0.0.1
  httpPort: 5700
  webSocketPort: 8080
  groupPeriod: 60 # 群组消息定时发送